name: Django CD

on:
  workflow_run:
    workflows: ["Django CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get the run ID from the previous workflow
      - name: Get run ID
        id: get_run_id
        uses: actions/github-script@v4
        with:
          script: echo ${{ needs.upload.outputs.run_id }}

      # Download artifacts from CI workflow
      - name: Download CI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: kid-coder-api-package
          run-id: ${{ steps.get_run_id.outputs.run_id }}

      - name: Configure SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ github.workspace }}/packaged-project ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:/home/ubuntu/kids-coder-carnival
