name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    env:
      DJANGO_PROJECT_PATH: $GITHUB_WORKSPACE/kid-coder-carnival-api/kidcodercarnivalapi
      DJANGO_BUILD_NAME: $GITHUB_WORKSPACE/kid_coder_carnival_api_1.tar.gz

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/kid-coder-carnival-api/kidcodercarnivalapi/requirements.txt
    - name: Exclude unnecessary files
      run: |
        # Example: Exclude development settings file
        rm -f $DJANGO_PROJECT_PATH/development_settings.py

    - name: Package project
      run: |
        # Navigate to the directory containing the project files
        cd $GITHUB_WORKSPACE/kid-coder-carnival-api
        # Create the tarball file
        tar -czvf $GITHUB_WORKSPACE/kid_coder_carnival_api_1.tar.gz kidcodercarnivalapi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kid-coder-api-package-${{ github.sha }}
        path: "/home/runner/work/kid-coder-carnival/kid-coder-carnival/kid_coder_carnival_api_1.tar.gz"
        overwrite: true

      # Set the output variable with the run ID
    - name: Set run ID output
      id: set_run_id
      run: |
        echo "ci_run_id=${{ github.run_id }}" >> $GITHUB_ENV
        echo "ci_artifact_name=kid-coder-api-package-${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download artifacts from CI workflow
      - name: Download CI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{env.ci_artifact_name}}
          run-id: ${{ env.ci_run_id }}

      - name: Configure SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp -i "${{ secrets.SSH_PRIVATE_KEY }}" ff.ff ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:/home/ubuntu/kids-coder-carnival
