name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    env:
      DJANGO_PROJECT_PATH: ${GITHUB_WORKSPACE}/kid-coder-carnival-api/kidcodercarnivalapi

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${DJANGO_PROJECT_PATH}/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Exclude unnecessary files
      run: |
        # Example: Exclude development settings file
        rm -f $DJANGO_PROJECT_PATH/development_settings.py
    - name: Package project
      run: tar -czvf ${GITHUB_WORKSPACE}/your_project.tar.gz $DJANGO_PROJECT_PATH
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: packaged-project
        path: $GITHUB_WORKSPACE/your_project.tar.gz
